### ISSUE TITLE
Descramble issue

### ISSUE THREAD

**Issue by Krylanc3lo** [Arias800/Fichier-divers#2]
Hey,

Effectivement c'est mieux et ca evitera le HS sur l'autre sujet.

Merci encore pour le code, cela fonctionne beaucoup mieux que ce que j'avais. Je n'ai plus qu'un seul scan qui ne marche pas (il y a une ligne horizontale qui est mal placee vers le bas): c'est prisonnier-riku

Je vais essayer d'adapter ce que tu m'as donne.

**Comment by Arias800** [comment]
Essayer de changer la valeur ligne 23 en mettant 210 a la place de 200 ^^
Je viens de tester et en faisant cette modif ca fonctionne correctement ^^

**Comment by Krylanc3lo** [comment]
Effectivement! Merci beaucoup pour l'aide rapide, ca m'evite de passer par hakuneko-desktop juste pour ce scan :)

**Comment by Arias800** [comment]
Tiens tu faisait la même chose que moi mais a mon avis tu va tomber sur beaucoup d'autre scan proteger ^^

**Comment by Krylanc3lo** [comment]
Oui je suis d'accord il va y en avoir de plus en plus... quelle galere haha

**Comment by Arias800** [comment]
Bof une fois que le bon code trouver ca passe tres bien ^^

**Comment by Krylanc3lo** [comment]
je te dirais si je tombe encore sur des cas bizarres. Now il reste plus qu'a regler le cas de CF sur les 2 autres threads et on est bon ^^

**Comment by Arias800** [comment]
Il y a peux de chance car j'ai deja effectuer par mal d'ajustement similaire sur le code pour l'ajuster et limite les erreur de detection ^^
